(function(){
const generators={
persentase:()=>{let price=rnd(50000,900000,10000),disc=rnd(10,60,5),ans=price*(1-disc/100);return make(`Sebuah jaket seharga Rp${fmt(price)} mendapat diskon ${disc}%. Berapa harga setelah diskon?`,ans, v=>`Rp${fmt(Math.round(v))}`)},
persamaan:()=>{let rate=rnd(2000,7000,500),dist=rnd(3,20),base=5000,ans=base+rate*dist;return make(`Ongkos perjalanan memiliki biaya dasar Rp${fmt(base)} dan tarif Rp${fmt(rate)}/km. Untuk ${dist} km, totalnya?`,ans,v=>`Rp${fmt(v)}`)},
geometri:()=>{let p=rnd(4,12),l=rnd(3,9),ans=p*l;return make(`Sebuah lantai berbentuk persegi panjang berukuran ${p} m × ${l} m. Berapa luasnya?`,ans,v=>`${v} m²`)},
statistik:()=>{let a=Array.from({length:5},()=>rnd(2,15)),ans=a.reduce((x,y)=>x+y,0)/5;return make(`Skor 5 pemain adalah ${a.join(', ')}. Berapa rata-ratanya?`,ans,v=>Number.isInteger(v)?`${v}`:v.toFixed(1))},
trigonometri:()=>{let d=rnd(5,25),angle=[30,45,60][rnd(0,2)],ans=d*Math.tan(angle*Math.PI/180);return make(`Dari jarak ${d} m, sudut elevasi puncak gedung ${angle}°. Berapa tinggi gedung kira-kira?`,ans,v=>`${v.toFixed(1)} m`)},
peluang:()=>{let sides=[6,8,10][rnd(0,2)],fav=rnd(1,Math.floor(sides/2)),ans=fav/sides;return make(`Sebuah dadu ${sides} sisi fair dilempar. Jika ${fav} sisi dianggap “menang”, peluang menang adalah…`,ans,v=>`${Math.round(v*100)}%`)}
};
function rnd(a,b,step=1){let n=Math.floor((b-a)/step)+1;return a+Math.floor(Math.random()*n)*step}function fmt(n){return new Intl.NumberFormat('id-ID').format(n)}
function make(text,answer,format){let correct=format(answer),nums=new Set([String(correct)]);let options=[correct];while(options.length<4){let delta=(Math.random()<.5?-1:1)*(Math.max(1,Math.round(Math.abs(answer)*[.05,.1,.15,.2][rnd(0,3)])));let v=answer+delta;if(v<0)continue;let s=format(v);if(!nums.has(String(s))){nums.add(String(s));options.push(s)}}for(let i=options.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}return {text,options,correct:options.indexOf(correct)}}
let state={};
document.addEventListener('DOMContentLoaded',()=>{startGame.onclick=begin;muteBtn.onclick=()=>{state.muted=!state.muted;muteBtn.textContent=state.muted?'🔇 Suara OFF':'🔊 Suara ON'};loadLeaderboard()});
function sound(name){if(state.muted)return;const a=new Audio('assets/sfx/'+name+'.mp3');a.volume=.35;a.play().catch(()=>{})}
function begin(){let name=playerName.value.trim()||'Pemain';state={...state,name,topic:gameTopic.value,level:gameLevel.value,n:0,score:0,correct:0,muted:state.muted||false};gameSetup.classList.add('hidden');gameResult.classList.add('hidden');gamePlay.classList.remove('hidden');sound('start');next()}
function next(){if(state.n>=8)return finish();state.q=generators[state.topic]();state.time={pemula:20,menengah:12,jagoan:8}[state.level];state.max=state.time;renderQuestion();clearInterval(state.timer);state.timer=setInterval(()=>{state.time-=.1;document.querySelector('.timer-fill').style.width=Math.max(0,state.time/state.max*100)+'%';if(state.time<=0){clearInterval(state.timer);answer(-1)}},100)}
function renderQuestion(){gamePlay.innerHTML=`<div class="game-top"><span>Soal ${state.n+1}/8</span><span>⭐ ${state.score} poin</span></div><div class="timer-track"><div class="timer-fill"></div></div><div class="game-question">${state.q.text}</div><div class="game-options">${state.q.options.map((o,i)=>`<button class="game-option" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div class="feedback" id="feedback"></div>`;gamePlay.querySelectorAll('.game-option').forEach(b=>b.onclick=()=>answer(+b.dataset.i))}
function answer(choice){if(state.answered)return;state.answered=true;clearInterval(state.timer);let good=choice===state.q.correct;if(good){state.correct++;let mult={pemula:1,menengah:1.5,jagoan:2.2}[state.level];let speedBonus=Math.max(0,Math.round(state.time/state.max*50));state.score+=Math.round(100*mult+speedBonus);sound('correct')}else sound('wrong');gamePlay.querySelectorAll('.game-option').forEach((b,i)=>{b.disabled=true;if(i===state.q.correct)b.classList.add('correct');if(i===choice&&i!==state.q.correct)b.classList.add('wrong')});document.getElementById('feedback').textContent=good?'✅ Benar! + poin':'❌ Jawaban yang benar: '+state.q.options[state.q.correct];setTimeout(()=>{state.answered=false;state.n++;next()},900)}
async function finish(){gamePlay.classList.add('hidden');let percent=Math.round(state.correct/8*100);gameResult.classList.remove('hidden');gameResult.innerHTML=`<div class="eyebrow" style="text-align:center">SELESAI!</div><div class="result-score" id="countScore">0</div><h3 style="text-align:center">${state.correct}/8 benar · ${percent}%</h3><p style="text-align:center">${percent>=88?'🔥 Gila, kamu jago banget!':percent>=63?'🚀 Mantap! Tinggal sedikit lagi menuju skor sempurna.':'🌱 Tetap semangat! Coba modul materinya lalu main lagi.'}</p><div style="display:flex;gap:10px"><button class="gradient-btn wide" id="again">Main Lagi</button><button class="soft-btn wide" id="change">Ganti Materi</button></div>`;animateScore(state.score);sound('end');let rec={topic:state.topic,level:state.level,score:state.score,correct:state.correct,total:8,percent,date:new Date().toISOString()};localStorage.setItem('mdny_leaderboard',JSON.stringify([...(JSON.parse(localStorage.getItem('mdny_leaderboard')||'[]')), {...rec,name:state.name}].sort((a,b)=>b.score-a.score).slice(0,10)));if(window.saveGameToCloud)saveGameToCloud(rec,state.name);loadLeaderboard()}
function animateScore(target){let x=0,el=document.getElementById('countScore'),t=setInterval(()=>{x+=Math.max(1,Math.ceil((target-x)/8));el.textContent=x;if(x>=target)clearInterval(t)},35)}
function loadLeaderboard(){let rows=JSON.parse(localStorage.getItem('mdny_leaderboard')||'[]');leaderboard.innerHTML=rows.length?rows.map((r,i)=>`<div class="leaderboard-row"><span class="rank">#${i+1}</span><strong>${esc(r.name||'Pemain')}</strong><span>${r.score} pts</span><span>${r.percent}%</span></div>`).join(''):'<p style="color:var(--muted)">Belum ada skor. Jadilah yang pertama!</p>'}
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.addEventListener('click',e=>{if(e.target.id==='again')begin();if(e.target.id==='change'){gameResult.classList.add('hidden');gameSetup.classList.remove('hidden')}})
})();