(function(){
const modules=[
{id:'persentase',name:'Persentase',case:'Diskon Kilat',accent:'#FF9F1C',icon:'🏷️',desc:'Hitung diskon, kenaikan harga, dan persentase yang sering muncul saat belanja.'},
{id:'persamaan',name:'Persamaan',case:'Biaya Perjalanan',accent:'#3B82F6',icon:'🚌',desc:'Gunakan variabel dan persamaan untuk menghitung ongkos perjalanan.'},
{id:'geometri',name:'Geometri',case:'Studio Desain Rumah',accent:'#7C3AED',icon:'📐',desc:'Pakai luas, keliling, dan volume saat merancang ruang dan benda.'},
{id:'statistik',name:'Statistik',case:'Data Pertandingan',accent:'#17C3B2',icon:'📊',desc:'Baca data pertandingan lewat mean, median, modus, dan range.'},
{id:'trigonometri',name:'Trigonometri',case:'Tinggi Gedung',accent:'#F2C94C',icon:'🏙️',desc:'Perkirakan tinggi gedung dengan sudut dan perbandingan sisi.'},
{id:'peluang',name:'Peluang',case:'Simulator Peluang',accent:'#E33E57',icon:'🎲',desc:'Kenali peluang dari dadu, koin, dan pengambilan benda.'}];
window.MODULES=modules;window.currentModule=null;
document.addEventListener('DOMContentLoaded',()=>{
const cards=document.getElementById('moduleCards');cards.innerHTML=modules.map(m=>`<article class="module-card" style="--accent:${m.accent}"><div class="module-num">${m.icon} MODUL</div><h3>${m.name}</h3><strong>${m.case}</strong><p>${m.desc}</p><button data-open="${m.id}">Buka modul →</button></article>`).join('');
cards.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModule(b.dataset.open));
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
});
window.showPanel=function(id){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='home'&&window.Progress)Progress.render();};
function switchTab(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+tab));if(tab==='materi'&&currentModule)Progress.setMateri(currentModule.id)}
window.openModule=function(id){const m=modules.find(x=>x.id===id);currentModule=m;showPanel('moduleView');document.getElementById('moduleHeader').innerHTML=`<div class="module-head" style="--accent:${m.accent}"><div><div class="eyebrow">${m.icon} ${m.case.toUpperCase()}</div><h2>${m.name}</h2><p>${m.desc}</p></div><button class="back-btn" onclick="showPanel('modules')">← Kembali</button></div>`;document.getElementById('tab-materi').innerHTML=window.getModuleMaterial(id);document.getElementById('tab-coba').innerHTML=window.getModuleSimulator(id);window.bindSimulator(id);window.renderQuiz(id);Progress.setMateri(id);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='materi'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-materi'))}
window.getModuleMaterial=function(id){
const accent=modules.find(m=>m.id===id).accent;
const lessons={
persentase:{
intro:`<h3>🏷️ Apa itu persentase?</h3><p>Persentase adalah cara menyatakan suatu bagian dari keseluruhan dalam <b>100 bagian</b>. Dalam kehidupan sehari-hari, persentase sering dipakai untuk diskon, kenaikan harga, pajak, cashback, keuntungan, dan perubahan harga.</p><p>Modul ini fokus pada <b>persentase dalam sistem diskon</b> — mulai dari diskon tunggal sampai kasus yang paling sering bikin salah hitung: diskon berturut-turut dan promo yang terlihat lebih besar dari aslinya.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Diskon tunggal</h4><p>Diskon yang diberikan satu kali dari harga awal.</p><b>Harga akhir = harga awal − diskon</b></div><div class="concept-box"><h4>Diskon berturut (ganda)</h4><p>Diskon kedua dihitung dari harga <i>setelah</i> diskon pertama, bukan dari harga awal.</p><b>20% + 10% ≠ 30%</b></div><div class="concept-box"><h4>Reverse discount</h4><p>Mencari harga awal kalau yang diketahui adalah harga setelah diskon.</p><b>Harga awal = harga akhir ÷ (1 − diskon)</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">Diskon = persentase diskon × harga awal</div><div class="formula">Harga akhir = harga awal × (1 − persentase diskon)</div><div class="formula">Harga awal = harga akhir ÷ (1 − persentase diskon)</div><div class="formula">Diskon berturut-turut: Harga akhir = harga awal × (1 − a) × (1 − b)</div></div>`,
example:`<h3>🛍️ Contoh: Diskon tunggal</h3><p>Jaket seharga Rp300.000 mendapat diskon 20%.</p><ol class="step-list"><li>Besar diskon = 20% × Rp300.000 = <b>Rp60.000</b>.</li><li>Harga setelah diskon = Rp300.000 − Rp60.000 = <b>Rp240.000</b>.</li></ol><h3>🔥 Contoh: Diskon berturut-turut</h3><p>Harga awal Rp500.000, mendapat diskon 20% + 10%.</p><ol class="step-list"><li>Diskon pertama: 20% × Rp500.000 = Rp100.000 → harga jadi <b>Rp400.000</b>.</li><li>Diskon kedua dihitung dari Rp400.000: 10% × Rp400.000 = Rp40.000 → harga akhir <b>Rp360.000</b>.</li><li>Total pengurangan Rp140.000, jadi diskon sebenarnya = 140.000 ÷ 500.000 × 100% = <b>28%</b>, bukan 30%.</li></ol><h3>🔄 Contoh: Mencari harga awal (reverse)</h3><p>Sepatu setelah diskon 20% harganya Rp400.000. Berapa harga awalnya?</p><ol class="step-list"><li>Diskon 20% berarti pelanggan membayar 80% dari harga awal.</li><li>Harga awal = Rp400.000 ÷ 0,8 = <b>Rp500.000</b>.</li></ol><h3>⚠️ Contoh: Jebakan promo "Diskon 50% + 20%"</h3><p>Harga awal Rp1.000.000, promo diskon 50% + 20%.</p><ol class="step-list"><li>Diskon 50%: Rp1.000.000 × 50% = Rp500.000 → harga jadi <b>Rp500.000</b>.</li><li>Diskon 20% dari Rp500.000: Rp100.000 → harga akhir <b>Rp400.000</b>.</li><li>Total pengurangan Rp600.000, jadi diskon efektifnya <b>60%</b>, bukan 70%.</li></ol><h3>🧾 Contoh belanja nyata</h3><p>Sebuah tas Rp800.000 dapat promo diskon 30% + 10%.</p><ol class="step-list"><li>Diskon 30%: Rp800.000 × 30% = Rp240.000 → harga jadi Rp560.000.</li><li>Diskon 10% dari Rp560.000: Rp56.000 → harga akhir <b>Rp504.000</b>.</li><li>Bukan Rp800.000 × 70% = Rp560.000 — itu cara yang salah.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Kenapa promo diskon ganda menyesatkan?</b><p>Tulisan "50% + 20%" terlihat seperti dijumlah jadi 70%. Padahal mekanismenya bertahap: harga awal → diskon 50% → harga baru → diskon 20% → harga akhir. Setiap diskon berikutnya bekerja pada harga yang sudah berubah, jadi diskon berturut-turut tidak boleh dijumlahkan begitu saja.</p></div><table class="mini-table"><tr><th>Kondisi</th><th>Cara menghitung</th></tr><tr><td>Diskon tunggal</td><td>Harga awal × persentase diskon</td></tr><tr><td>Harga setelah diskon</td><td>Harga awal × (1 − diskon)</td></tr><tr><td>Diskon berturut-turut</td><td>Hitung satu per satu, bertahap</td></tr><tr><td>Mencari harga awal</td><td>Harga akhir ÷ (1 − diskon)</td></tr><tr><td>Promo 20% + 10%</td><td>Bukan 30%</td></tr><tr><td>Promo 50% + 20%</td><td>Bukan 70%</td></tr></table>`,
tip:`💡 <b>Poin penting:</b> diskon 20% + 10% ≠ 30%, dan diskon 50% + 20% ≠ 70%. Pada diskon berturut-turut, diskon berikutnya selalu dihitung dari harga setelah diskon sebelumnya — bukan dari harga awal.`},
persamaan:{
intro:`<h3>📌 Apa itu persamaan?</h3><p>Persamaan adalah kalimat matematika yang menyatakan bahwa dua nilai <b>sama</b>. Biasanya ada nilai yang belum diketahui dan kita wakili dengan variabel, misalnya <b>x</b>.</p><p>Di dunia nyata, persamaan sangat berguna untuk mencari biaya, jarak, waktu, jumlah barang, atau nilai lain yang belum diketahui. Kuncinya adalah menerjemahkan cerita menjadi hubungan matematika.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Variabel</h4><p>Huruf yang mewakili nilai yang belum diketahui.</p><b>x = jarak perjalanan</b></div><div class="concept-box"><h4>Koefisien</h4><p>Angka yang mengalikan variabel.</p><b>3.000x → tarif per km</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">Biaya total = biaya tetap + (tarif × jumlah)</div><div class="formula">ax + b = c → x = (c − b) ÷ a</div></div>`,
example:`<h3>🚌 Contoh: Biaya perjalanan</h3><p>Biaya awal bus Rp10.000. Setiap kilometer menambah Rp2.500. Jika kamu membayar Rp25.000, berapa kilometer perjalananmu?</p><ol class="step-list"><li>Misalkan jarak = <b>x</b> km.</li><li>Buat persamaan: 10.000 + 2.500x = 25.000.</li><li>Kurangi 10.000 dari kedua sisi: 2.500x = 15.000.</li><li>Bagi 2.500: <b>x = 6 km</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Cara mengecek jawaban:</b><p>Masukkan x = 6 ke rumus: 10.000 + (2.500 × 6) = 25.000. Karena hasilnya sesuai, jawaban kita masuk akal.</p></div>`,
tip:`💡 <b>Tips:</b> jangan takut dengan x. Anggap x hanya sebagai “kotak kosong” yang harus ditemukan. Tulis informasi dari cerita sebelum membuat persamaan.`},
geometri:{
intro:`<h3>📌 Geometri ada di ruang yang kita pakai</h3><p>Geometri mempelajari bentuk, ukuran, jarak, luas, keliling, dan volume. Saat kamu mendesain kamar, menghitung jumlah keramik, mengecat dinding, atau membuat kemasan, kamu sebenarnya sedang menggunakan geometri.</p><p>Pilih rumus berdasarkan pertanyaannya: <b>keliling</b> untuk panjang sisi luar, <b>luas</b> untuk permukaan, dan <b>volume</b> untuk ruang yang dapat diisi.</p>`,
concept:`<table class="mini-table"><tr><th>Bentuk</th><th>Luas</th><th>Keliling</th></tr><tr><td>Persegi</td><td>s²</td><td>4s</td></tr><tr><td>Persegi panjang</td><td>p × l</td><td>2(p+l)</td></tr><tr><td>Segitiga</td><td>½ × a × t</td><td>jumlah semua sisi</td></tr><tr><td>Lingkaran</td><td>πr²</td><td>2πr</td></tr></table>`,
formula:`<div class="formula-stack"><div class="formula">Persegi panjang: L = p × l</div><div class="formula">Balok: V = p × l × t</div><div class="formula">Lingkaran: L = πr²</div></div>`,
example:`<h3>🏠 Contoh: Keramik kamar</h3><p>Sebuah kamar berukuran 5 m × 4 m. Jika satu dus keramik menutup 2 m², berapa dus minimal yang dibutuhkan?</p><ol class="step-list"><li>Luas kamar = 5 × 4 = <b>20 m²</b>.</li><li>Jumlah dus = 20 ÷ 2 = <b>10 dus</b>.</li><li>Dalam pembelian nyata, tambahkan cadangan untuk potongan atau kerusakan.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Perhatikan satuan!</b><p>Jika panjang dalam meter, luas menjadi m². Jangan mencampur cm dengan m tanpa konversi terlebih dahulu.</p></div>`,
tip:`💡 <b>Tips:</b> gambar bentuknya dan tulis ukuran yang diketahui di dekat sisinya. Visual sederhana sering membuat soal geometri jauh lebih mudah.`},
statistik:{
intro:`<h3>📌 Apa itu statistika data tunggal?</h3><p>Statistika digunakan untuk mengolah dan memahami sekumpulan data. Materi ini fokus pada <b>data tunggal</b>, yaitu data yang ditampilkan satu per satu dan belum dikelompokkan ke dalam interval kelas.</p><p>Contoh data tunggal — nilai ujian: <b>70, 75, 80, 80, 85, 90, 95</b>. Karena masih ditulis sebagai nilai individu, kita bisa langsung mencari mean, median, modus, dan range-nya.</p><p>Catatan: data yang sudah dirangkum dalam tabel interval (misalnya 60–69, 70–79, dst.) disebut <b>data berkelompok</b> dan dibahas di materi terpisah.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Mean</h4><p>Jumlah semua data dibagi banyak data.</p><b>Σx ÷ n</b></div><div class="concept-box"><h4>Median (ganjil)</h4><p>Data tengah setelah diurutkan.</p><b>Ambil satu nilai tengah</b></div><div class="concept-box"><h4>Median (genap)</h4><p>Rata-rata dua data tengah setelah diurutkan.</p><b>(tengah 1 + tengah 2) ÷ 2</b></div><div class="concept-box"><h4>Modus</h4><p>Nilai yang paling sering muncul.</p><b>Bisa lebih dari satu.</b></div><div class="concept-box"><h4>Range</h4><p>Jarak antara nilai terbesar dan terkecil.</p><b>maks − min</b></div><div class="concept-box"><h4>Outlier</h4><p>Nilai yang jauh berbeda dari sebagian besar data.</p><b>Bisa membuat mean menyesatkan</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">Mean = Σx ÷ n</div><div class="formula">Median (n ganjil) = data ke-(n+1)÷2 setelah diurutkan</div><div class="formula">Median (n genap) = (data tengah 1 + data tengah 2) ÷ 2</div><div class="formula">Range = nilai terbesar − nilai terkecil</div></div>`,
example:`<h3>📈 Contoh: Mean</h3><p>Data skor: 70, 75, 80, 85, 90.</p><ol class="step-list"><li>Jumlahkan semua data: 70 + 75 + 80 + 85 + 90 = <b>400</b>.</li><li>Banyak data (n) = <b>5</b>.</li><li>Mean = 400 ÷ 5 = <b>80</b>.</li></ol><h3>📍 Contoh: Median (data ganjil)</h3><p>Data: 60, 70, 75, 80, 90 (n = 5, ganjil).</p><ol class="step-list"><li>Data sudah terurut dari kecil ke besar.</li><li>Karena n ganjil, ambil data tengah (data ke-3).</li><li>Median = <b>75</b>.</li></ol><h3>📍 Contoh: Median (data genap)</h3><p>Data: 60, 70, 75, 80, 90, 100 (n = 6, genap).</p><ol class="step-list"><li>Karena n genap, tidak ada satu nilai yang tepat di tengah.</li><li>Ambil dua nilai tengah: <b>75 dan 80</b>.</li><li>Median = (75 + 80) ÷ 2 = <b>77,5</b>.</li></ol><h3>⚠️ Contoh: Outlier</h3><p>Data: 70, 72, 75, 76, 77, 200. Hampir semua data ada di sekitar 70–77, kecuali satu nilai yang sangat jauh: 200.</p><ol class="step-list"><li>Mean = (70+72+75+76+77+200) ÷ 6 = 570 ÷ 6 = <b>95</b>.</li><li>Median (dua data tengah 75 dan 76) = (75+76) ÷ 2 = <b>75,5</b>.</li><li>Mean tertarik naik jadi 95 karena nilai 200, padahal sebagian besar data cuma di sekitar 70–77. Median (75,5) jauh lebih mewakili kondisi mayoritas data.</li></ol><h3>📐 Contoh: Range</h3><p>Data: 60, 65, 70, 75, 90.</p><ol class="step-list"><li>Nilai terbesar = <b>90</b>, nilai terkecil = <b>60</b>.</li><li>Range = 90 − 60 = <b>30</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Contoh nyata: gaji karyawan</b><p>Gaji 5 orang: Rp4 juta, Rp4 juta, Rp5 juta, Rp5 juta, Rp100 juta. Mean-nya Rp23,6 juta — padahal itu tidak menggambarkan gaji kebanyakan orang di kelompok ini. Median-nya Rp5 juta, jauh lebih mewakili kondisi mayoritas karena tidak terlalu terpengaruh satu nilai yang sangat besar.</p></div><table class="mini-table"><tr><th>Ukuran</th><th>Fungsi</th></tr><tr><td>Mean</td><td>Mengetahui nilai rata-rata</td></tr><tr><td>Median</td><td>Mengetahui nilai tengah</td></tr><tr><td>Modus</td><td>Mengetahui nilai yang paling sering muncul</td></tr><tr><td>Range</td><td>Mengetahui jarak nilai terbesar dan terkecil</td></tr><tr><td>Outlier</td><td>Nilai yang jauh berbeda dari data lainnya</td></tr></table>`,
tip:`💡 <b>Poin penting:</b> gunakan mean untuk gambaran rata-rata secara umum, median saat ada nilai ekstrem/outlier, modus untuk nilai yang paling sering muncul, dan range untuk melihat rentang data. Selalu urutkan data dulu sebelum mencari median.`},
trigonometri:{
intro:`<h3>📌 Trigonometri dan pengukuran tinggi</h3><p>Trigonometri membahas hubungan antara sudut dan sisi pada segitiga, terutama segitiga siku-siku. Dengan konsep ini, kita bisa memperkirakan tinggi objek yang sulit diukur langsung.</p><p>Untuk siswa, tiga rasio penting adalah <b>sin, cos, dan tan</b>. Ingat pola sederhana: <b>SOH–CAH–TOA</b>.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>SOH</h4><p>Sin = Opposite / Hypotenuse</p><b>sin θ = depan / miring</b></div><div class="concept-box"><h4>CAH</h4><p>Cos = Adjacent / Hypotenuse</p><b>cos θ = samping / miring</b></div><div class="concept-box"><h4>TOA</h4><p>Tan = Opposite / Adjacent</p><b>tan θ = depan / samping</b></div><div class="concept-box"><h4>Pythagoras</h4><p>Untuk segitiga siku-siku.</p><b>a² + b² = c²</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">sin θ = depan ÷ miring</div><div class="formula">cos θ = samping ÷ miring</div><div class="formula">tan θ = depan ÷ samping</div></div>`,
example:`<h3>🏙️ Contoh: Tinggi gedung</h3><p>Kamu berdiri 12 m dari kaki gedung dan mengukur sudut elevasi ke puncak sebesar 45°. Abaikan tinggi mata untuk model sederhana.</p><ol class="step-list"><li>Yang dicari adalah sisi depan (tinggi).</li><li>Yang diketahui sisi samping = 12 m.</li><li>Gunakan tan: tan 45° = tinggi ÷ 12.</li><li>Karena tan 45° = 1, tinggi = <b>12 m</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Catatan dunia nyata:</b><p>Pengukuran sebenarnya perlu memperhitungkan tinggi mata, kemiringan tanah, ketelitian alat, dan posisi pengamat. Contoh di atas adalah model sederhana untuk memahami konsep.</p></div>`,
tip:`💡 <b>Tips mengingat:</b> gambar segitiga dulu. Tandai sudut, sisi depan, sisi samping, dan sisi miring sebelum memilih rumus.`},
peluang:{
intro:`<h3>📌 Peluang = seberapa mungkin sesuatu terjadi</h3><p>Peluang digunakan saat hasil belum pasti, misalnya lempar dadu, koin, undian, atau permainan. Nilai peluang berada dari <b>0 sampai 1</b>, atau 0% sampai 100%.</p><p>Peluang 0 berarti mustahil, sedangkan peluang 1 berarti pasti. Semakin dekat ke 1, semakin besar kemungkinan peristiwa tersebut terjadi.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Ruang sampel</h4><p>Semua hasil yang mungkin terjadi.</p><b>Dadu → {1,2,3,4,5,6}</b></div><div class="concept-box"><h4>Kejadian</h4><p>Hasil yang kita inginkan.</p><b>Genap → {2,4,6}</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">P(A) = banyak hasil yang diinginkan ÷ banyak seluruh hasil</div><div class="formula">0 ≤ P(A) ≤ 1</div><div class="formula">P(A) dalam persen = P(A) × 100%</div></div>`,
example:`<h3>🎲 Contoh: Lempar dadu</h3><p>Sebuah dadu fair dilempar sekali. Berapa peluang muncul angka genap?</p><ol class="step-list"><li>Semua hasil: 1, 2, 3, 4, 5, 6 → ada <b>6</b>.</li><li>Hasil genap: 2, 4, 6 → ada <b>3</b>.</li><li>P(genap) = 3 ÷ 6 = <b>½ = 50%</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Kenapa “fair” penting?</b><p>Rumus sederhana ini menganggap setiap hasil memiliki kesempatan yang sama. Dadu yang berat sebelah atau koin yang tidak seimbang tidak memenuhi asumsi tersebut.</p></div>`,
tip:`💡 <b>Tips:</b> tulis ruang sampel sebelum menghitung. Jangan langsung menebak peluang hanya dari perasaan.`}
};
const x=lessons[id];
return `<div class="lesson-sections"><div class="content-card">${x.intro}</div><div class="content-card">${x.concept}</div><div class="content-card"><h3>📐 Rumus penting</h3>${x.formula}</div><div class="content-card">${x.example}</div><div class="content-card">${x.extra}<div class="tip" style="margin-top:14px">${x.tip}</div></div></div>`;
};

})();