(function(){
const modules=[
{id:'persentase',name:'Persentase',case:'Diskon Kilat',accent:'#FF9F1C',icon:'🏷️',desc:'Hitung diskon, kenaikan harga, dan persentase yang sering muncul saat belanja.'},
{id:'persamaan',name:'Persamaan',case:'Biaya Perjalanan',accent:'#3B82F6',icon:'🚌',desc:'Gunakan variabel dan persamaan untuk menghitung ongkos perjalanan.'},
{id:'geometri',name:'Geometri',case:'Studio Desain Rumah',accent:'#7C3AED',icon:'📐',desc:'Pakai luas, keliling, dan volume saat merancang ruang dan benda.'},
{id:'statistik',name:'Statistik',case:'Data Pertandingan',accent:'#17C3B2',icon:'📊',desc:'Baca data pertandingan lewat mean, median, modus, dan range.'},
{id:'trigonometri',name:'Trigonometri',case:'Tinggi Gedung',accent:'#F2C94C',icon:'🏙️',desc:'Perkirakan tinggi gedung dengan sudut dan perbandingan sisi.'},
{id:'peluang',name:'Peluang',case:'Simulator Peluang',accent:'#E33E57',icon:'🎲',desc:'Kenali peluang dari dadu, koin, dan pengambilan benda.'}];
window.MODULES=modules;window.currentModule=null;
document.addEventListener('DOMContentLoaded',()=>{
const cards=document.getElementById('moduleCards');cards.innerHTML=modules.map(m=>`<article class="module-card" style="--accent:${m.accent}"><div class="module-num">${m.icon} MODUL</div><h3>${m.name}</h3><strong>${m.case}</strong><p>${m.desc}</p><button data-open="${m.id}">Buka modul →</button></article>`).join('');
cards.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModule(b.dataset.open));
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
});
window.showPanel=function(id){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='home'&&window.Progress)Progress.render();};
function switchTab(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+tab));if(tab==='materi'&&currentModule)Progress.setMateri(currentModule.id)}
window.openModule=function(id){const m=modules.find(x=>x.id===id);currentModule=m;showPanel('moduleView');document.getElementById('moduleHeader').innerHTML=`<div class="module-head" style="--accent:${m.accent}"><div><div class="eyebrow">${m.icon} ${m.case.toUpperCase()}</div><h2>${m.name}</h2><p>${m.desc}</p></div><button class="back-btn" onclick="showPanel('modules')">← Kembali</button></div>`;document.getElementById('tab-materi').innerHTML=window.getModuleMaterial(id);document.getElementById('tab-coba').innerHTML=window.getModuleSimulator(id);window.bindSimulator(id);window.renderQuiz(id);Progress.setMateri(id);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='materi'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-materi'))}
window.getModuleMaterial=function(id){
const accent=modules.find(m=>m.id===id).accent;
const lessons={
persentase:{
intro:`<h3>🏷️ Apa itu persentase?</h3><p>Persentase adalah cara menyatakan suatu bagian dari keseluruhan dalam <b>100 bagian</b>. Dalam kehidupan sehari-hari, persentase sering dipakai untuk diskon, kenaikan harga, pajak, cashback, keuntungan, dan perubahan harga.</p><p>Modul ini fokus pada <b>persentase dalam sistem diskon</b> — mulai dari diskon tunggal sampai kasus yang paling sering bikin salah hitung: diskon berturut-turut dan promo yang terlihat lebih besar dari aslinya.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Diskon tunggal</h4><p>Diskon yang diberikan satu kali dari harga awal.</p><b>Harga akhir = harga awal − diskon</b></div><div class="concept-box"><h4>Diskon berturut (ganda)</h4><p>Diskon kedua dihitung dari harga <i>setelah</i> diskon pertama, bukan dari harga awal.</p><b>20% + 10% ≠ 30%</b></div><div class="concept-box"><h4>Reverse discount</h4><p>Mencari harga awal kalau yang diketahui adalah harga setelah diskon.</p><b>Harga awal = harga akhir ÷ (1 − diskon)</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">Diskon = persentase diskon × harga awal</div><div class="formula">Harga akhir = harga awal × (1 − persentase diskon)</div><div class="formula">Harga awal = harga akhir ÷ (1 − persentase diskon)</div><div class="formula">Diskon berturut-turut: Harga akhir = harga awal × (1 − a) × (1 − b)</div></div>`,
example:`<h3>🛍️ Contoh: Diskon tunggal</h3><p>Jaket seharga Rp300.000 mendapat diskon 20%.</p><ol class="step-list"><li>Besar diskon = 20% × Rp300.000 = <b>Rp60.000</b>.</li><li>Harga setelah diskon = Rp300.000 − Rp60.000 = <b>Rp240.000</b>.</li></ol><h3>🔥 Contoh: Diskon berturut-turut</h3><p>Harga awal Rp500.000, mendapat diskon 20% + 10%.</p><ol class="step-list"><li>Diskon pertama: 20% × Rp500.000 = Rp100.000 → harga jadi <b>Rp400.000</b>.</li><li>Diskon kedua dihitung dari Rp400.000: 10% × Rp400.000 = Rp40.000 → harga akhir <b>Rp360.000</b>.</li><li>Total pengurangan Rp140.000, jadi diskon sebenarnya = 140.000 ÷ 500.000 × 100% = <b>28%</b>, bukan 30%.</li></ol><h3>🔄 Contoh: Mencari harga awal (reverse)</h3><p>Sepatu setelah diskon 20% harganya Rp400.000. Berapa harga awalnya?</p><ol class="step-list"><li>Diskon 20% berarti pelanggan membayar 80% dari harga awal.</li><li>Harga awal = Rp400.000 ÷ 0,8 = <b>Rp500.000</b>.</li></ol><h3>⚠️ Contoh: Jebakan promo "Diskon 50% + 20%"</h3><p>Harga awal Rp1.000.000, promo diskon 50% + 20%.</p><ol class="step-list"><li>Diskon 50%: Rp1.000.000 × 50% = Rp500.000 → harga jadi <b>Rp500.000</b>.</li><li>Diskon 20% dari Rp500.000: Rp100.000 → harga akhir <b>Rp400.000</b>.</li><li>Total pengurangan Rp600.000, jadi diskon efektifnya <b>60%</b>, bukan 70%.</li></ol><h3>🧾 Contoh belanja nyata</h3><p>Sebuah tas Rp800.000 dapat promo diskon 30% + 10%.</p><ol class="step-list"><li>Diskon 30%: Rp800.000 × 30% = Rp240.000 → harga jadi Rp560.000.</li><li>Diskon 10% dari Rp560.000: Rp56.000 → harga akhir <b>Rp504.000</b>.</li><li>Bukan Rp800.000 × 70% = Rp560.000 — itu cara yang salah.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Kenapa promo diskon ganda menyesatkan?</b><p>Tulisan "50% + 20%" terlihat seperti dijumlah jadi 70%. Padahal mekanismenya bertahap: harga awal → diskon 50% → harga baru → diskon 20% → harga akhir. Setiap diskon berikutnya bekerja pada harga yang sudah berubah, jadi diskon berturut-turut tidak boleh dijumlahkan begitu saja.</p></div><table class="mini-table"><tr><th>Kondisi</th><th>Cara menghitung</th></tr><tr><td>Diskon tunggal</td><td>Harga awal × persentase diskon</td></tr><tr><td>Harga setelah diskon</td><td>Harga awal × (1 − diskon)</td></tr><tr><td>Diskon berturut-turut</td><td>Hitung satu per satu, bertahap</td></tr><tr><td>Mencari harga awal</td><td>Harga akhir ÷ (1 − diskon)</td></tr><tr><td>Promo 20% + 10%</td><td>Bukan 30%</td></tr><tr><td>Promo 50% + 20%</td><td>Bukan 70%</td></tr></table>`,
tip:`💡 <b>Poin penting:</b> diskon 20% + 10% ≠ 30%, dan diskon 50% + 20% ≠ 70%. Pada diskon berturut-turut, diskon berikutnya selalu dihitung dari harga setelah diskon sebelumnya — bukan dari harga awal.`},
persamaan:{
intro:`<h3>📌 Apa itu persamaan?</h3><p>Persamaan adalah kalimat matematika yang menyatakan bahwa dua nilai <b>sama</b>. Biasanya ada nilai yang belum diketahui dan kita wakili dengan variabel, misalnya <b>x</b>.</p><p>Di dunia nyata, persamaan sangat berguna untuk mencari biaya, jarak, waktu, jumlah barang, atau nilai lain yang belum diketahui. Kuncinya adalah menerjemahkan cerita menjadi hubungan matematika.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Variabel</h4><p>Huruf yang mewakili nilai yang belum diketahui.</p><b>x = jarak perjalanan</b></div><div class="concept-box"><h4>Koefisien</h4><p>Angka yang mengalikan variabel.</p><b>3.000x → tarif per km</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">Biaya total = biaya tetap + (tarif × jumlah)</div><div class="formula">ax + b = c → x = (c − b) ÷ a</div></div>`,
example:`<h3>🚌 Contoh: Biaya perjalanan</h3><p>Biaya awal bus Rp10.000. Setiap kilometer menambah Rp2.500. Jika kamu membayar Rp25.000, berapa kilometer perjalananmu?</p><ol class="step-list"><li>Misalkan jarak = <b>x</b> km.</li><li>Buat persamaan: 10.000 + 2.500x = 25.000.</li><li>Kurangi 10.000 dari kedua sisi: 2.500x = 15.000.</li><li>Bagi 2.500: <b>x = 6 km</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Cara mengecek jawaban:</b><p>Masukkan x = 6 ke rumus: 10.000 + (2.500 × 6) = 25.000. Karena hasilnya sesuai, jawaban kita masuk akal.</p></div>`,
tip:`💡 <b>Tips:</b> jangan takut dengan x. Anggap x hanya sebagai “kotak kosong” yang harus ditemukan. Tulis informasi dari cerita sebelum membuat persamaan.`},
geometri:{
intro:`<h3>📌 Geometri ada di ruang yang kita pakai</h3><p>Geometri mempelajari bentuk, ukuran, jarak, luas, keliling, dan volume. Saat kamu mendesain kamar, menghitung jumlah keramik, mengecat dinding, atau membuat kemasan, kamu sebenarnya sedang menggunakan geometri.</p><p>Pilih rumus berdasarkan pertanyaannya: <b>keliling</b> untuk panjang sisi luar, <b>luas</b> untuk permukaan, dan <b>volume</b> untuk ruang yang dapat diisi.</p>`,
concept:`<table class="mini-table"><tr><th>Bentuk</th><th>Luas</th><th>Keliling</th></tr><tr><td>Persegi</td><td>s²</td><td>4s</td></tr><tr><td>Persegi panjang</td><td>p × l</td><td>2(p+l)</td></tr><tr><td>Segitiga</td><td>½ × a × t</td><td>jumlah semua sisi</td></tr><tr><td>Lingkaran</td><td>πr²</td><td>2πr</td></tr></table>`,
formula:`<div class="formula-stack"><div class="formula">Persegi panjang: L = p × l</div><div class="formula">Balok: V = p × l × t</div><div class="formula">Lingkaran: L = πr²</div></div>`,
example:`<h3>🏠 Contoh: Keramik kamar</h3><p>Sebuah kamar berukuran 5 m × 4 m. Jika satu dus keramik menutup 2 m², berapa dus minimal yang dibutuhkan?</p><ol class="step-list"><li>Luas kamar = 5 × 4 = <b>20 m²</b>.</li><li>Jumlah dus = 20 ÷ 2 = <b>10 dus</b>.</li><li>Dalam pembelian nyata, tambahkan cadangan untuk potongan atau kerusakan.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Perhatikan satuan!</b><p>Jika panjang dalam meter, luas menjadi m². Jangan mencampur cm dengan m tanpa konversi terlebih dahulu.</p></div>`,
tip:`💡 <b>Tips:</b> gambar bentuknya dan tulis ukuran yang diketahui di dekat sisinya. Visual sederhana sering membuat soal geometri jauh lebih mudah.`},
statistik:{
intro:`<h3>📌 Apa itu statistika data tunggal?</h3><p>Statistika digunakan untuk mengolah dan memahami sekumpulan data. Materi ini fokus pada <b>data tunggal</b>, yaitu data yang ditampilkan satu per satu dan belum dikelompokkan ke dalam interval kelas.</p><p>Contoh data tunggal — nilai ujian: <b>70, 75, 80, 80, 85, 90, 95</b>. Karena masih ditulis sebagai nilai individu, kita bisa langsung mencari mean, median, modus, dan range-nya.</p><p>Catatan: data yang sudah dirangkum dalam tabel interval (misalnya 60–69, 70–79, dst.) disebut <b>data berkelompok</b> dan dibahas di materi terpisah.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Mean</h4><p>Jumlah semua data dibagi banyak data.</p><b>Σx ÷ n</b></div><div class="concept-box"><h4>Median (ganjil)</h4><p>Data tengah setelah diurutkan.</p><b>Ambil satu nilai tengah</b></div><div class="concept-box"><h4>Median (genap)</h4><p>Rata-rata dua data tengah setelah diurutkan.</p><b>(tengah 1 + tengah 2) ÷ 2</b></div><div class="concept-box"><h4>Modus</h4><p>Nilai yang paling sering muncul.</p><b>Bisa lebih dari satu.</b></div><div class="concept-box"><h4>Range</h4><p>Jarak antara nilai terbesar dan terkecil.</p><b>maks − min</b></div><div class="concept-box"><h4>Outlier</h4><p>Nilai yang jauh berbeda dari sebagian besar data.</p><b>Bisa membuat mean menyesatkan</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">Mean = Σx ÷ n</div><div class="formula">Median (n ganjil) = data ke-(n+1)÷2 setelah diurutkan</div><div class="formula">Median (n genap) = (data tengah 1 + data tengah 2) ÷ 2</div><div class="formula">Range = nilai terbesar − nilai terkecil</div></div>`,
example:`<h3>📈 Contoh: Mean</h3><p>Data skor: 70, 75, 80, 85, 90.</p><ol class="step-list"><li>Jumlahkan semua data: 70 + 75 + 80 + 85 + 90 = <b>400</b>.</li><li>Banyak data (n) = <b>5</b>.</li><li>Mean = 400 ÷ 5 = <b>80</b>.</li></ol><h3>📍 Contoh: Median (data ganjil)</h3><p>Data: 60, 70, 75, 80, 90 (n = 5, ganjil).</p><ol class="step-list"><li>Data sudah terurut dari kecil ke besar.</li><li>Karena n ganjil, ambil data tengah (data ke-3).</li><li>Median = <b>75</b>.</li></ol><h3>📍 Contoh: Median (data genap)</h3><p>Data: 60, 70, 75, 80, 90, 100 (n = 6, genap).</p><ol class="step-list"><li>Karena n genap, tidak ada satu nilai yang tepat di tengah.</li><li>Ambil dua nilai tengah: <b>75 dan 80</b>.</li><li>Median = (75 + 80) ÷ 2 = <b>77,5</b>.</li></ol><h3>⚠️ Contoh: Outlier</h3><p>Data: 70, 72, 75, 76, 77, 200. Hampir semua data ada di sekitar 70–77, kecuali satu nilai yang sangat jauh: 200.</p><ol class="step-list"><li>Mean = (70+72+75+76+77+200) ÷ 6 = 570 ÷ 6 = <b>95</b>.</li><li>Median (dua data tengah 75 dan 76) = (75+76) ÷ 2 = <b>75,5</b>.</li><li>Mean tertarik naik jadi 95 karena nilai 200, padahal sebagian besar data cuma di sekitar 70–77. Median (75,5) jauh lebih mewakili kondisi mayoritas data.</li></ol><h3>📐 Contoh: Range</h3><p>Data: 60, 65, 70, 75, 90.</p><ol class="step-list"><li>Nilai terbesar = <b>90</b>, nilai terkecil = <b>60</b>.</li><li>Range = 90 − 60 = <b>30</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Contoh nyata: gaji karyawan</b><p>Gaji 5 orang: Rp4 juta, Rp4 juta, Rp5 juta, Rp5 juta, Rp100 juta. Mean-nya Rp23,6 juta — padahal itu tidak menggambarkan gaji kebanyakan orang di kelompok ini. Median-nya Rp5 juta, jauh lebih mewakili kondisi mayoritas karena tidak terlalu terpengaruh satu nilai yang sangat besar.</p></div><table class="mini-table"><tr><th>Ukuran</th><th>Fungsi</th></tr><tr><td>Mean</td><td>Mengetahui nilai rata-rata</td></tr><tr><td>Median</td><td>Mengetahui nilai tengah</td></tr><tr><td>Modus</td><td>Mengetahui nilai yang paling sering muncul</td></tr><tr><td>Range</td><td>Mengetahui jarak nilai terbesar dan terkecil</td></tr><tr><td>Outlier</td><td>Nilai yang jauh berbeda dari data lainnya</td></tr></table>`,
tip:`💡 <b>Poin penting:</b> gunakan mean untuk gambaran rata-rata secara umum, median saat ada nilai ekstrem/outlier, modus untuk nilai yang paling sering muncul, dan range untuk melihat rentang data. Selalu urutkan data dulu sebelum mencari median.`},
trigonometri:{
intro:`<h3>📌 Trigonometri: hubungan sudut, sisi, dan dunia nyata</h3><p><b>Trigonometri</b> adalah cabang matematika yang mempelajari hubungan antara <b>sudut</b> dan <b>panjang sisi</b>. Trigonometri digunakan untuk mengukur tinggi gedung atau pohon, menentukan kemiringan, membuat desain bangunan, pemetaan, navigasi, astronomi, robotika, komputer grafis, animasi, game, dan gelombang.</p><p>Materi ini membahas konsep dasar sampai lanjutan: segitiga siku-siku, perbandingan trigonometri, derajat dan radian, sudut istimewa, kuadran, lingkaran satuan, identitas, sudut berelasi, jumlah dan selisih sudut, sudut ganda, setengah sudut, aturan sinus dan cosinus, fungsi dan grafik, persamaan, pertidaksamaan, serta penerapan.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>🔺 Segitiga siku-siku</h4><p>Segitiga dengan satu sudut 90°. Sisi di depan sudut 90° disebut <b>sisi miring/hipotenusa</b>.</p></div><div class="concept-box"><h4>📐 Sudut</h4><p>Ukuran putaran. Satuan yang sering dipakai adalah <b>derajat (°)</b> dan <b>radian</b>.</p></div><div class="concept-box"><h4>⭕ Lingkaran satuan</h4><p>Lingkaran berjari-jari 1 untuk memahami sin dan cos pada berbagai sudut.</p></div><div class="concept-box"><h4>📈 Fungsi trigonometri</h4><p>Sin, cos, dan tan dapat dipandang sebagai fungsi yang nilainya berubah mengikuti sudut.</p></div></div>`,
formula:`<div class="formula-stack"><div class="formula">sin θ = sisi depan ÷ sisi miring</div><div class="formula">cos θ = sisi samping ÷ sisi miring</div><div class="formula">tan θ = sisi depan ÷ sisi samping</div><div class="formula">tan θ = sin θ ÷ cos θ</div><div class="formula">sin² θ + cos² θ = 1</div><div class="formula">180° = π radian</div></div>`,
example:`<h3>🔺 1. Mengenal sisi pada segitiga siku-siku</h3><p>Nama sisi ditentukan berdasarkan sudut yang diperhatikan. Terhadap sudut θ terdapat sisi depan, sisi samping, dan sisi miring.</p><div class="concept-grid"><div class="concept-box"><h4>Sisi miring</h4><p>Sisi yang berhadapan dengan sudut 90° dan merupakan sisi terpanjang.</p></div><div class="concept-box"><h4>Sisi depan</h4><p>Sisi yang berhadapan langsung dengan sudut θ.</p></div><div class="concept-box"><h4>Sisi samping</h4><p>Sisi yang menempel pada sudut θ selain sisi miring.</p></div></div><p>Misalnya sisi depan = 3 dan sisi samping = 4. Dengan Pythagoras, c² = 3² + 4² = 25 sehingga c = 5. Maka sin θ = 3/5, cos θ = 4/5, dan tan θ = 3/4.</p>`,
extra:`<div class="real-life" style="--accent:${accent}"><h3>📏 2. Derajat dan radian</h3><p><b>Derajat</b> membagi satu putaran menjadi 360°, sedangkan <b>radian</b> menyatakan ukuran sudut berdasarkan busur lingkaran.</p><div class="formula-stack"><div class="formula">1 putaran = 360° = 2π rad</div><div class="formula">180° = π rad</div><div class="formula">90° = π/2 rad</div><div class="formula">60° = π/3 rad</div><div class="formula">45° = π/4 rad</div><div class="formula">30° = π/6 rad</div></div><p>Derajat → radian: kalikan π/180. Radian → derajat: kalikan 180/π. Contoh 120° = <b>2π/3 rad</b> dan 3π/4 rad = <b>135°</b>.</p></div>
<div class="content-card"><h3>⭐ 3. Sudut istimewa</h3><p>Nilai sudut istimewa sering digunakan untuk menyelesaikan soal tanpa kalkulator.</p><table class="mini-table"><tr><th>Sudut</th><th>0°</th><th>30°</th><th>45°</th><th>60°</th><th>90°</th></tr><tr><th>Radian</th><td>0</td><td>π/6</td><td>π/4</td><td>π/3</td><td>π/2</td></tr><tr><td>sin</td><td>0</td><td>1/2</td><td>√2/2</td><td>√3/2</td><td>1</td></tr><tr><td>cos</td><td>1</td><td>√3/2</td><td>√2/2</td><td>1/2</td><td>0</td></tr><tr><td>tan</td><td>0</td><td>√3/3</td><td>1</td><td>√3</td><td>tidak terdefinisi</td></tr></table><p>Cara cepat mengingat sin: <b>√0/2, √1/2, √2/2, √3/2, √4/2</b>. Nilai cos adalah urutan kebalikannya.</p></div>
<div class="content-card"><h3>🧭 4. Kuadran dan tanda fungsi</h3><p>Untuk sudut lebih dari 90°, gunakan kuadran. Tanda fungsi bergantung pada posisi sudut.</p><table class="mini-table"><tr><th>Kuadran</th><th>Rentang</th><th>sin</th><th>cos</th><th>tan</th></tr><tr><td>I</td><td>0°–90°</td><td>+</td><td>+</td><td>+</td></tr><tr><td>II</td><td>90°–180°</td><td>+</td><td>−</td><td>−</td></tr><tr><td>III</td><td>180°–270°</td><td>−</td><td>−</td><td>+</td></tr><tr><td>IV</td><td>270°–360°</td><td>−</td><td>+</td><td>−</td></tr></table><p>Contoh: sin 150° = sin(180°−30°) = <b>1/2</b>. Karena cos negatif di kuadran II, cos 150° = <b>−√3/2</b>.</p></div>
<div class="content-card"><h3>⭕ 5. Lingkaran satuan</h3><p>Lingkaran satuan berpusat di (0,0) dan berjari-jari 1. Jika titik P(x,y) berada pada sudut θ, maka:</p><div class="formula-stack"><div class="formula">x = cos θ</div><div class="formula">y = sin θ</div><div class="formula">tan θ = y/x, dengan x ≠ 0</div></div><p>Karena koordinat pada lingkaran satuan berada antara −1 dan 1, maka <b>−1 ≤ sin θ ≤ 1</b> dan <b>−1 ≤ cos θ ≤ 1</b>.</p></div>
<div class="content-card"><h3>🧩 6. Identitas trigonometri</h3><p>Identitas adalah persamaan yang benar untuk semua nilai sudut yang memenuhi syarat. Identitas digunakan untuk menyederhanakan atau membuktikan bentuk trigonometri.</p><div class="formula-stack"><div class="formula">sin²x + cos²x = 1</div><div class="formula">1 + tan²x = sec²x</div><div class="formula">1 + cot²x = csc²x</div><div class="formula">tan x = sin x/cos x</div><div class="formula">cot x = cos x/sin x</div><div class="formula">sec x = 1/cos x</div><div class="formula">csc x = 1/sin x</div></div><p>Contoh: (1−cos²x)/sin x = sin²x/sin x = <b>sin x</b>, dengan syarat sin x ≠ 0.</p></div>
<div class="content-card"><h3>➕ 7. Jumlah dan selisih sudut</h3><p>Rumus ini berguna untuk sudut seperti 75° atau 15° yang dapat dipecah menjadi dua sudut istimewa.</p><div class="formula-stack"><div class="formula">sin(a+b) = sin a cos b + cos a sin b</div><div class="formula">sin(a−b) = sin a cos b − cos a sin b</div><div class="formula">cos(a+b) = cos a cos b − sin a sin b</div><div class="formula">cos(a−b) = cos a cos b + sin a sin b</div><div class="formula">tan(a+b) = (tan a + tan b)/(1 − tan a tan b)</div><div class="formula">tan(a−b) = (tan a − tan b)/(1 + tan a tan b)</div></div><p>Contoh: 75° = 45° + 30°. Masukkan nilai sudut istimewa ke rumus sin atau cos jumlah sudut.</p></div>
<div class="content-card"><h3>2️⃣ 8. Sudut ganda</h3><p>Sudut ganda adalah sudut berbentuk 2x.</p><div class="formula-stack"><div class="formula">sin 2x = 2 sin x cos x</div><div class="formula">cos 2x = cos²x − sin²x</div><div class="formula">cos 2x = 2cos²x − 1</div><div class="formula">cos 2x = 1 − 2sin²x</div><div class="formula">tan 2x = 2tan x/(1 − tan²x)</div></div><p>Jika sin x = 3/5 dan x di kuadran I, cos x = 4/5. Maka sin 2x = <b>24/25</b>.</p></div>
<div class="content-card"><h3>½ 9. Setengah sudut</h3><p>Rumus setengah sudut digunakan untuk mencari sin(x/2), cos(x/2), atau tan(x/2).</p><div class="formula-stack"><div class="formula">sin²(x/2) = (1 − cos x)/2</div><div class="formula">cos²(x/2) = (1 + cos x)/2</div><div class="formula">tan²(x/2) = (1 − cos x)/(1 + cos x)</div></div><p>Setelah memperoleh nilai kuadrat, tentukan tanda hasil berdasarkan kuadran sudut.</p></div>
<div class="content-card"><h3>🔄 10. Sudut negatif dan sudut berelasi</h3><p>Hubungan berikut membantu menyederhanakan sudut besar atau negatif.</p><div class="formula-stack"><div class="formula">sin(−x) = −sin x</div><div class="formula">cos(−x) = cos x</div><div class="formula">tan(−x) = −tan x</div><div class="formula">sin(180°−x) = sin x</div><div class="formula">cos(180°−x) = −cos x</div><div class="formula">tan(180°−x) = −tan x</div><div class="formula">sin(180°+x) = −sin x</div><div class="formula">cos(180°+x) = −cos x</div><div class="formula">tan(180°+x) = tan x</div><div class="formula">sin(360°−x) = −sin x</div><div class="formula">cos(360°−x) = cos x</div><div class="formula">tan(360°−x) = −tan x</div></div></div>
<div class="content-card"><h3>📐 11. Aturan sinus dan cosinus</h3><p>Untuk segitiga yang tidak harus siku-siku, gunakan aturan sinus atau cosinus.</p><div class="formula-stack"><div class="formula">a/sin A = b/sin B = c/sin C</div><div class="formula">a² = b² + c² − 2bc cos A</div><div class="formula">b² = a² + c² − 2ac cos B</div><div class="formula">c² = a² + b² − 2ab cos C</div></div><p><b>Aturan sinus</b> cocok ketika tersedia pasangan sisi dan sudut yang berhadapan. <b>Aturan cosinus</b> cocok ketika diketahui dua sisi dan sudut apit, atau tiga sisi untuk mencari sudut.</p></div>
<div class="content-card"><h3>📈 12. Fungsi dan grafik trigonometri</h3><p>Tiga fungsi dasar adalah y = sin x, y = cos x, dan y = tan x.</p><div class="concept-grid"><div class="concept-box"><h4>y = sin x</h4><p>Range −1 sampai 1, amplitudo 1, periode 360° atau 2π.</p></div><div class="concept-box"><h4>y = cos x</h4><p>Range −1 sampai 1, amplitudo 1, periode 360° atau 2π.</p></div><div class="concept-box"><h4>y = tan x</h4><p>Periode 180° atau π dan memiliki asimtot saat cos x = 0.</p></div></div><p>Untuk y = A sin(Bx+C)+D atau y = A cos(Bx+C)+D:</p><div class="formula-stack"><div class="formula">Amplitudo = |A|</div><div class="formula">Periode = 360°/|B| atau 2π/|B|</div><div class="formula">Pergeseran vertikal = D</div></div><p>Untuk y = A tan(Bx+C)+D, periode = <b>180°/|B|</b> atau <b>π/|B|</b>.</p></div>
<div class="content-card"><h3>✏️ 13. Persamaan trigonometri</h3><p>Persamaan trigonometri memuat sin, cos, atau tan dan biasanya diselesaikan pada interval tertentu.</p><ol class="step-list"><li>Sederhanakan menjadi bentuk seperti sin x = k, cos x = k, atau tan x = k.</li><li>Cari sudut acuan.</li><li>Tentukan kuadran berdasarkan tanda fungsi.</li><li>Tulis semua solusi pada interval yang diminta.</li><li>Periksa kembali bila diperlukan.</li></ol><p>Contoh: sin x = 1/2 pada 0° ≤ x ≤ 360°. Sudut acuan 30°, sin positif di kuadran I dan II, sehingga <b>x = 30° dan 150°</b>.</p><p>Contoh: cos x = −√2/2. Sudut acuan 45°, cos negatif di kuadran II dan III, sehingga <b>x = 135° dan 225°</b>.</p></div>
<div class="content-card"><h3>🧠 14. Pertidaksamaan trigonometri</h3><p>Pertidaksamaan membandingkan nilai fungsi, misalnya sin x ≥ 1/2. Gunakan grafik atau lingkaran satuan untuk menentukan interval.</p><p>Contoh pada 0° ≤ x ≤ 360°: sin x ≥ 1/2 dipenuhi pada <b>30° ≤ x ≤ 150°</b>. Perhatikan apakah tanda ≥ atau ≤ membuat titik batas ikut menjadi solusi.</p></div>
<div class="content-card"><h3>🔍 15. Fungsi invers trigonometri</h3><p>Fungsi invers digunakan untuk mencari sudut ketika nilai sin, cos, atau tan diketahui.</p><div class="formula-stack"><div class="formula">θ = sin⁻¹(y)</div><div class="formula">θ = cos⁻¹(y)</div><div class="formula">θ = tan⁻¹(y)</div></div><p>Contoh: tan θ = 1/√3 dan θ sudut lancip, maka θ = <b>30°</b>. Pastikan kalkulator berada pada mode <b>DEG</b> jika jawaban diminta dalam derajat atau <b>RAD</b> untuk radian.</p></div>
<div class="content-card"><h3>🔁 16. Transformasi grafik</h3><p>Koefisien pada fungsi trigonometri dapat mengubah amplitudo, periode, dan posisi grafik.</p><div class="formula-stack"><div class="formula">y = sin x + D → bergeser vertikal D</div><div class="formula">y = A sin x → amplitudo |A|</div><div class="formula">y = sin(Bx) → periode 360°/|B|</div><div class="formula">y = sin(x−C) → bergeser C ke kanan</div><div class="formula">y = sin(x+C) → bergeser C ke kiri</div></div><p>Untuk membuat sketsa, tentukan periode lalu tentukan titik maksimum, minimum, titik tengah, dan titik potong sumbu.</p></div>
<div class="content-card"><h3>🌍 17. Penerapan trigonometri di dunia nyata</h3><ul><li><b>Tinggi gedung atau pohon:</b> sudut elevasi dan jarak horizontal.</li><li><b>Kemiringan jalan:</b> hubungan tinggi dan jarak menggunakan tan.</li><li><b>Arsitektur dan konstruksi:</b> sudut dan panjang rangka.</li><li><b>Pemetaan dan navigasi:</b> posisi dan jarak berdasarkan arah.</li><li><b>Robotika:</b> posisi lengan robot berdasarkan panjang dan sudut.</li><li><b>Komputer grafis dan game:</b> rotasi, gerakan melingkar, arah, dan animasi.</li><li><b>Gelombang:</b> pola periodik seperti getaran dan suara.</li></ul><h4>🏙️ Contoh: mengukur tinggi gedung</h4><p>Seseorang berdiri 20 m dari kaki gedung dan mengukur sudut elevasi 40°. Tinggi mata diabaikan.</p><ol class="step-list"><li>Sisi samping = 20 m dan sisi depan = h.</li><li>tan 40° = h/20.</li><li>h = 20 tan 40°.</li><li>Dengan kalkulator, h ≈ <b>16,78 m</b>.</li></ol><p>Jika tinggi mata pengamat 1,5 m, model sederhananya memberikan tinggi gedung sekitar <b>18,28 m</b>.</p></div>
<div class="content-card"><h3>📝 18. Ringkasan rumus penting</h3><table class="mini-table"><tr><th>Topik</th><th>Rumus</th></tr><tr><td>Perbandingan</td><td>sin = depan/miring; cos = samping/miring; tan = depan/samping</td></tr><tr><td>Hubungan</td><td>tan x = sin x/cos x</td></tr><tr><td>Identitas</td><td>sin²x + cos²x = 1</td></tr><tr><td>Jumlah sin</td><td>sin(a+b) = sin a cos b + cos a sin b</td></tr><tr><td>Selisih sin</td><td>sin(a−b) = sin a cos b − cos a sin b</td></tr><tr><td>Jumlah cos</td><td>cos(a+b) = cos a cos b − sin a sin b</td></tr><tr><td>Selisih cos</td><td>cos(a−b) = cos a cos b + sin a sin b</td></tr><tr><td>Sudut ganda</td><td>sin 2x = 2sin x cos x</td></tr><tr><td>Sudut ganda</td><td>cos 2x = 1−2sin²x = 2cos²x−1</td></tr><tr><td>Aturan sinus</td><td>a/sin A = b/sin B = c/sin C</td></tr><tr><td>Aturan cosinus</td><td>a² = b²+c²−2bc cos A</td></tr><tr><td>Sin/cos</td><td>Periode = 360°/|B| atau 2π/|B|</td></tr><tr><td>Tan</td><td>Periode = 180°/|B| atau π/|B|</td></tr></table></div>
<div class="content-card"><h3>💡 Cara belajar trigonometri</h3><ol class="step-list"><li>Pahami sisi depan, samping, dan miring.</li><li>Kuasai 0°, 30°, 45°, 60°, dan 90°.</li><li>Pahami empat kuadran dan tanda fungsi.</li><li>Latih identitas secara bertahap.</li><li>Pelajari jumlah-selisih, sudut ganda, dan setengah sudut.</li><li>Untuk persamaan, gunakan lingkaran satuan atau grafik.</li><li>Untuk soal cerita, gambar sketsa terlebih dahulu.</li><li>Periksa mode kalkulator: DEG atau RAD.</li></ol><p><b>Kesimpulan:</b> trigonometri bukan sekadar hafalan rumus. Pahami hubungan antara <b>sudut, sisi, kuadran, identitas, persamaan, dan grafik</b>.</p></div>`
},
peluang:{
intro:`<h3>📌 Peluang = seberapa mungkin sesuatu terjadi</h3><p>Peluang digunakan saat hasil belum pasti, misalnya lempar dadu, koin, undian, atau permainan. Nilai peluang berada dari <b>0 sampai 1</b>, atau 0% sampai 100%.</p><p>Peluang 0 berarti mustahil, sedangkan peluang 1 berarti pasti. Semakin dekat ke 1, semakin besar kemungkinan peristiwa tersebut terjadi.</p>`,
concept:`<div class="concept-grid"><div class="concept-box"><h4>Ruang sampel</h4><p>Semua hasil yang mungkin terjadi.</p><b>Dadu → {1,2,3,4,5,6}</b></div><div class="concept-box"><h4>Kejadian</h4><p>Hasil yang kita inginkan.</p><b>Genap → {2,4,6}</b></div></div>`,
formula:`<div class="formula-stack"><div class="formula">P(A) = banyak hasil yang diinginkan ÷ banyak seluruh hasil</div><div class="formula">0 ≤ P(A) ≤ 1</div><div class="formula">P(A) dalam persen = P(A) × 100%</div></div>`,
example:`<h3>🎲 Contoh: Lempar dadu</h3><p>Sebuah dadu fair dilempar sekali. Berapa peluang muncul angka genap?</p><ol class="step-list"><li>Semua hasil: 1, 2, 3, 4, 5, 6 → ada <b>6</b>.</li><li>Hasil genap: 2, 4, 6 → ada <b>3</b>.</li><li>P(genap) = 3 ÷ 6 = <b>½ = 50%</b>.</li></ol>`,
extra:`<div class="real-life" style="--accent:${accent}"><b>Kenapa “fair” penting?</b><p>Rumus sederhana ini menganggap setiap hasil memiliki kesempatan yang sama. Dadu yang berat sebelah atau koin yang tidak seimbang tidak memenuhi asumsi tersebut.</p></div>`,
tip:`💡 <b>Tips:</b> tulis ruang sampel sebelum menghitung. Jangan langsung menebak peluang hanya dari perasaan.`}
};
const x=lessons[id];
return `<div class="lesson-sections"><div class="content-card">${x.intro}</div><div class="content-card">${x.concept}</div><div class="content-card"><h3>📐 Rumus penting</h3>${x.formula}</div><div class="content-card">${x.example}</div><div class="content-card">${x.extra}<div class="tip" style="margin-top:14px">${x.tip}</div></div></div>`;
};

})();